---

- name: Install hello-node smoke test
  git:
    repo: 'https://github.com/benmangold/tower-of-hanoi.git'
    dest: /home/{{ user }}/github/tower-of-hanoi
    version: dev
  become_user: "{{ user }}"

- name: Install dependencies
  shell: npm i; npm i -g pm2
  args:
    chdir: /home/{{ user }}/github/tower-of-hanoi
    
- name: Build and start
  shell: npm run build; npx pm2 start server.js
  args:
    chdir: /home/{{ user }}/github/tower-of-hanoi.js
