---

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Create postgres user
  postgresql_user: name={{ user }} password={{ db_password }}
  become_user: postgres

- name: Create postgres database
  become_user: postgres
  postgresql_db:
    name: "{{ user }}"

- name: Connect to ubuntu database, create ubuntu user, and grant access
  become_user: postgres
  postgresql_user:
    db: "{{ user }}"
    name: "{{ db_name }}"
    password: "{{ db_password }}"
    encrypted: yes
    priv: "ALL"
